### ISSUE TITLE
DefaultTargetHandler simulation borders leave the screen

### ISSUE THREAD

**Issue by pHaC9** [J1blCblu/LockOnTarget#10]
I tried implementing the plugin in UE 5.1.0, in a default Third Person project, following the Initial Setup wiki page. I assigned the Target Handler Implementation in my character's LockOnTarget component as the Default Target Handler already provided, however, when simulating it in the Gameplay Debugger, its borders leave the screen, appearing as follows:
 

![Captura de tela 2023-01-24 182802](https://user-images.githubusercontent.com/43501459/214423634-284d1379-91a7-45bf-800a-f3b0e80e3c92.png)

I expected a closed rectangle on the screen, is this behaviour normal?

**Comment by pHaC9** [comment]
No changes were made to the Default Target Handler parameters.

**Comment by J1blCblu** [comment]
As I see, the Gameplay Debugger layout is also broken, the resolution of which is used to display primitives. This shouldn't break the core system, as long as the engine layout isn't broken as well.

Does it break when you activate the LockOnTarget category?

I have plans to rework the debugger (add more general info, change keypress to mouse wheel scroll, etc.). I'll investigate this issue during the rework.

**Comment by pHaC9** [comment]
Just checked it out, and no, the debugger layout does not change when activating/deactivating the category. I also tried disabling the plugin to see if something changed, but the problem persists. Maybe something on the engine itself?

**Comment by J1blCblu** [comment]
No longer relevant, drawing borders was removed in 1.6.0.
