### ISSUE TITLE
Compilation errors on Linux for Version 1.4.0 - 5.0 

### ISSUE THREAD

**Issue by MSlockbo** [J1blCblu/LockOnTarget#14]
The team I am on has been using this plugin in our Unreal project, and we have started looking into making builds for Linux, however, we are getting compilation errors. I attempted to update to 1.4.2, however, the same compilation issues would still occur. I have attached a log file detailing the errors.
[UBT-Kilonova-Linux-Shipping.txt](https://github.com/J1blCblu/LockOnTarget/files/12719438/UBT-Kilonova-Linux-Shipping.txt)

**Comment by J1blCblu** [comment]
Hello, I'll take a look into this issue after downloading the 5.0 engine. Will probably publish it with the upcoming update within a week since plenty of issues have been fixed since 1.4.x.

**Comment by MSlockbo** [comment]
Alright, thank you for taking the time to look into this.

**Comment by J1blCblu** [comment]
Have fixed compilation errors in 1.4.3. You can get the release [here](https://github.com/J1blCblu/LockOnTarget/releases/tag/v1.4.3-5.0).

Unfortunately, I wasn't able to port the latest update to 5.0 as it contains backwards-incompatible assets and too many changes to the Unreal source code. Although it's possible with some cuts if you remove the LockOnTargetDev and LockOnTargetEditor modules and change LockOnTargetDefines.h a little.

**Comment by MSlockbo** [comment]
This was more than enough, thank you so much. I was able to get a build working today.
