### ISSUE TITLE
Please continue to update

### ISSUE THREAD

**Issue by Hunanbean-Collective** [J1blCblu/LockOnTarget#15]
Please continue to update this plugin as UE evolves. we are on release 5.3.1 currently. Thank you

**Comment by JimPhoenix** [comment]
Yes please & thank you for your hard work! <3

**Comment by J1blCblu** [comment]
The plugin support isn't abandoned. My old PC burned down around 3 weeks ago and I finally decided to get a new one.

Just published an update, you can check it out [here](https://github.com/J1blCblu/LockOnTarget/releases/tag/v1.6.0-5.3). I'll update the documentation within a week and publish an update on the marketplace once my account is unlocked.
