### ISSUE TITLE
Lock Widget not working on packaged game.

### ISSUE THREAD

**Issue by macodys** [J1blCblu/LockOnTarget#17]
I have tried to build my game using this plugin, but the widget doesn't seem to render.

**Comment by J1blCblu** [comment]
It's a known issue. You can refer [here](https://github.com/J1blCblu/LockOnTarget/wiki/Frequently-Asked-Questions-(FAQs)#missing-cooked-content-in-shipping-builds).

**Comment by macodys** [comment]
Thanks!
