### ISSUE TITLE
That component didn’t persist when I restart UE5.0.1

### ISSUE THREAD

**Issue by oivio** [J1blCblu/LockOnTarget#2]
![image](https://user-images.githubusercontent.com/38628851/165078468-8e4891ee-8fc1-48f5-8953-5f6c0c665e4f.png)

`Component class is not set for 'LockOnTarget' - this component will not be instanced, and additional warnings or errors may occur when compiling Blueprint 'BP_ThirdPersonCharacter'.`

After adding a LockOnTarget component to BP_ThirdPersonCharacter ( C++ template ) it works fine but after restarting the project component is removed from "BP_ThirdPersonCharacter " and shows me the above error.

**Comment by J1blCblu** [comment]
I had the same issue with the NiagaraComponent, but I don't remember exactly how I fixed this.
Try these methods in any order :
* Rename the LockOnTarget to something else.
* Add a new LockOnTarget and remove the previous one.
* Duplicate the BP and delete the previous one.
* Reinstall the plugin.
* Delete temporary files in the project, like Intermediate, Binaries, DerivedDataCache, Saved.
* Reparent the BP to a lower class (etc. ACharacter) and parent it back to your class.

If the issue remains:
* Check the log for warnings or errors.
* Try to create another template project and check the component in it.

**Comment by oivio** [comment]
I did try on my other project but still same issue. Log:

```
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Marketplace/LockOnTarget/Content/' mounted to '/LockOnTarget/'
LogLinker: Warning: VerifyImport: Failed to find script package for import object 'Package /Script/LockOnTarget'
LogLinker: Warning: Unable to load LockOnComponent_GEN_VARIABLE with outer BlueprintGeneratedClass /Game/Blueprints/Characters/BP_BaseCharacter.BP_BaseCharacter_C because its class (LockOnTargetComponent) does not exist
LogBlueprint: Warning: [AssetLog] D:\Game\Project\Content\Blueprints\Characters\BP_BaseCharacter.uasset: [Compiler] Component class is not set for 'LockOnComponent' - this component will not be instanced, and additional warnings or errors may occur when compiling Blueprint 'BP_BaseCharacter'.
```

**Comment by J1blCblu** [comment]
Well, I've realized the problem. As you're using the C++ ThirdPerson template, the GameMode sets the DefaultPawn in its constructor via ConstructorHelpers::FClassFinder (which is bad, as you should set this up in the editor), which forces to load the CDO of the hard coded BP_ThirdPerson asset. But the LockOnTarget Plugin might not be iniatilized before creating the CDO for the GameMode, wich forces to load the CDO for the Character, which the editor actually uses. 

So you should remove this from the constructor and set this up in the editor.  (Create the new BP from the native GameMode and set it up in the *maps and modes* in the project settings or the *world settings*)
![image](https://user-images.githubusercontent.com/86853030/165587277-72761298-b832-473e-bf21-368667a3501b.png)  
![image](https://user-images.githubusercontent.com/86853030/165588108-fa196f48-e16a-4654-86c6-ed7440ee75fe.png)

You can read more about [Referencing Assets](https://docs.unrealengine.com/4.26/en-US/ProgrammingAndScripting/ProgrammingWithCPP/Assets/ReferencingAssets/).  

I'll try to change the loading phase of the plugin to PreDefault on the next week. Hope it'll also fix this issue.

**Comment by oivio** [comment]
thanks, looks like setting Default Pawn Class solved the issue.
