### ISSUE TITLE
Crash with Pawn Rotation Extension and character Physical animation

### ISSUE THREAD

**Issue by thetubby1** [J1blCblu/LockOnTarget#24]
I have a consistent crash or freeze to no response whenever I use the "Pawn Rotation Extension" and my character has physical animation enabled. Disabling physical animation allows the pawn rotation lock on to behave as intended but as soon as it is activated, I get a crash. UE5.3

-
Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Containers\Array.h] [Line: 771] Array index out of bounds: 4 from an array of size 0

UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

**Comment by J1blCblu** [comment]
Hi, the problem is that this extension has a tick group DuringPhysics. You can inherit from the extension in C++ and set it to PrePhysics. Anyway, I'm going to fix the accumulated bug reports and publish an update during the week.

**Comment by thetubby1** [comment]
Ah I see, im uncertain how to do that with my current project not being C++. If there will be an update to solve it then im ok waiting for that 😄. Appreciate the quick response!

**Comment by J1blCblu** [comment]
Just pushed an update to GitHub, but seems like you have to wait until Fab launches in mid October. I'm not able to submit file updates to the legacy portal.
